default_language_version:
  python: python3.9

default_stages: [commit]
default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          [
            "--profile=black",
            "--py=39",
            "--line-length=120",
            "--multi-line=3",
            "--trailing-comma",
            "--force-grid-wrap=0",
            "--use-parentheses",
            "--ensure-newline-before-comments",
            "--project=CORE,src,config,preprocess,train,transform,main,model",
          ]